adafruit/Adafruit_TinyUSB_Arduino

examples/HID/hid_composite/hid_composite.ino, src/Adafruit_USBD_HID.cpp, src/Adafruit_USBD_HID.h
Adafruit_USB_HID::keyboadReport -> keyboardReport.
=> Fix spelling error.

examples/HID/hid_generic_inout/hid_test.js
Its the same as proposed here: https://github.com/hathach/tinyusb/pull/78
=> Added node.js example which works on every OS

src/Adafruit_USBD_MIDI.cpp, src/Adafruit_USBD_MIDI.h
Add the raw packet interface wrapper for:
https://github.com/hathach/tinyusb/pull/258
=> Midi: add packet interface

examples/Composite/mouse_external_flash/mouse_external_flash.ino, examples/HID/hid_composite/hid_composite.ino, examples/HID/hid_generic_inout/hid_generic_inout.ino, examples/HID/hid_keyboard/hid_keyboard.ino, examples/HID/hid_mouse/hid_mouse.ino, examples/MIDI/midi_test/midi_test.ino, examples/MassStorage/msc_external_flash/msc_external_flash.ino, examples/MassStorage/msc_external_flash_sdcard/msc_external_flash_sdcard.ino, examples/WebUSB/webusb_rgb/webusb_rgb.ino, examples/WebUSB/webusb_serial/webusb_serial.ino, src/Adafruit_USBD_HID.cpp, src/Adafruit_USBD_HID.h, src/Adafruit_USBD_MIDI.h, src/Adafruit_USBD_MSC.h, src/Adafruit_USBD_WebUSB.h
change the HID INOUT endpoint order : 1st endpoint is IN, 2nd is OUT to compatible with cmsis-dap 
related to https://github.com/Seeed-Studio/Seeed_Arduino_DAPLink/pull/3
=> use setStringDescriptor() in example

examples/WebUSB/webusb_rgb/webusb_rgb.ino, examples/WebUSB/webusb_serial/webusb_serial.ino
explicitly add index.html to url #70
=> update url for webusb examples

src/arduino/hid/Adafruit_USBD_HID.cpp, src/arduino/ports/Adafruit_TinyUSB_nrf.cpp, src/class/audio/audio_device.c, src/class/hid/hid.h, src/class/hid/hid_device.c, src/class/hid/hid_device.h, src/common/tusb_fifo.c, src/device/dcd.h, src/device/usbd.c, src/device/usbd.h, src/device/usbd_pvt.h, src/portable/espressif/esp32sx/dcd_esp32sx.c, src/portable/nordic/nrf5x/dcd_nrf5x.c, src/portable/st/synopsys/dcd_synopsys.c, src/tusb.c, src/tusb.h, src/tusb_option.h
- update tinyusb to latest and fix warnings
=> Update tinyusb to latest and fix warings

changelog.md, examples/HID/hid_gamepad/hid_gamepad.ino
update gamepad example sketch to match new 32 buttons (from previously 16 buttons).
=> update gamepad example sketch

changelog.md, library.properties, src/arduino/ports/samd/tusb_config_samd.h
=> revert CFG_TUSB_DEBUG on samd port

examples/HID/hid_generic_inout/boards.js, examples/HID/hid_generic_inout/hid_test.js
- update node script to always shift dummy reportID like python 
- allow specify all product id with 0xFFFF in boards.js
follow up to #120
=> More hid inout

examples/Composite/mouse_ramdisk/mouse_ramdisk.ino, examples/HID/hid_boot_keyboard/hid_boot_keyboard.ino, examples/HID/hid_boot_mouse/hid_boot_mouse.ino, examples/HID/hid_composite/hid_composite.ino
update existing hid keyboard/mouse to hid_boot_keyboard/mouse
=> add hid boot examples

src/arduino/Adafruit_TinyUSB_API.h, src/arduino/Adafruit_USBD_CDC.cpp, src/arduino/Adafruit_USBD_CDC.h, src/class/audio/audio_device.c, src/class/bth/bth_device.c, src/class/cdc/cdc_device.c, src/class/msc/msc_device.c, src/common/tusb_common.h, src/common/tusb_compiler.h, src/common/tusb_types.h, src/device/dcd_attr.h, src/device/usbd.h, src/portable/nordic/nrf5x/dcd_nrf5x.c, src/portable/raspberrypi/rp2040/hcd_rp2040.c, src/tusb_option.h
=> fix nrf easy dma race condition

library.properties
add Adafruit InternalFlash into depends list for example building
=> run ci with msc_internal_flash_samd for metro m0

src/arduino/Adafruit_USBD_CDC.cpp
=> fix closing and reopening the serial interface

examples/CDC/cdc_multi/cdc_multi.ino, src/arduino/Adafruit_USBD_CDC.h
- check CFG_TUD_CDC to be at least 2
- add note that esp32-sx is not supported yet (more works needed).
=> update multiple cdc example

src/class/msc/msc_host.c, src/class/msc/msc_host.h
update tinyusb to commit https://github.com/hathach/tinyusb/commit/081e4eecba3c91f08cdf96b0a090e7726cec3727
=> update tinyusb to commit 081e4eecba3c91f08cdf96b0a090e7726cec3727

src/arduino/ports/rp2040/Adafruit_TinyUSB_rp2040.cpp, src/arduino/ports/rp2040/tusb_config_rp2040.h, tools/build_all.py
- use shared usb irq to trigger task runner, fix #187 
- also enable CFG_TUH_MSC for rp2040 (pio-usb)
=> Rp2040 enhance irq task runner

.github/ISSUE_TEMPLATE/bug_report.yml, src/arduino/midi/Adafruit_USBD_MIDI.cpp, src/arduino/midi/Adafruit_USBD_MIDI.h, src/arduino/ports/rp2040/tusb_config_rp2040.h
- enable CFG_TUH_CDC_LINE_CODING_ON_ENUM
- increase max midi cable to 16
=> Some enhance

examples/MassStorage/msc_ramdisk/ramdisk.h
The fix provide a better understanding of the FAT12 table
=> Fix FAT12 table and update comment

examples/DualRole/serial_host_bridge/serial_host_bridge.ino, src/arduino/cdc/Adafruit_USBH_CDC.cpp, src/arduino/cdc/Adafruit_USBH_CDC.h
change begin(idx) to setInterfaceIndex(idx), to allow using begin(baud) as other API. Update example accordingly
=> change Adafruit_USBH_CDC to inherit HardwareSerial (instead of Stream)

library.properties, src/Adafruit_TinyUSB.h, src/arduino/Adafruit_TinyUSB_API.cpp, src/arduino/Adafruit_TinyUSB_API.h, src/arduino/Adafruit_USBD_CDC.cpp, src/arduino/Adafruit_USBD_Device.cpp, src/arduino/hid/Adafruit_USBD_HID.cpp, src/arduino/midi/Adafruit_USBD_MIDI.cpp, src/arduino/msc/Adafruit_USBD_MSC.cpp, src/arduino/ports/esp32/Adafruit_TinyUSB_esp32.cpp, src/arduino/ports/nrf/Adafruit_TinyUSB_nrf.cpp, src/arduino/ports/rp2040/Adafruit_TinyUSB_rp2040.cpp, src/arduino/ports/samd/Adafruit_TinyUSB_samd.cpp, src/arduino/webusb/Adafruit_USBD_WebUSB.cpp
=> Release 2.0.0

src/arduino/ports/rp2040/Adafruit_TinyUSB_rp2040.cpp, src/portable/raspberrypi/rp2040/dcd_rp2040.c
=> fix build with mbed rp2040

.github/workflows/githubci.yml, .pre-commit-config.yaml, examples/DualRole/CDC/serial_host_bridge/serial_host_bridge.ino, examples/DualRole/HID/hid_device_report/hid_device_report.ino, examples/DualRole/HID/hid_remapper/hid_remapper.ino, examples/DualRole/MassStorage/msc_data_logger/msc_data_logger.ino, examples/DualRole/MassStorage/msc_file_explorer/msc_file_explorer.ino, examples/DualRole/device_info_rp2040/device_info_rp2040.ino, src/Adafruit_TinyUSB.h, src/arduino/Adafruit_USBH_Host.h, src/arduino/ports/rp2040/tusb_config_rp2040.h, src/class/cdc/cdc_host.c, src/class/cdc/cdc_host.h, src/class/hid/hid_host.c, src/class/hid/hid_host.h, src/device/usbd.c, src/host/usbh.c, src/host/usbh.h
update tinyusb to commit 07976ad26d4fbcad0694aa3a08294af7fd5f759f
=> More tinyusb update to commit 07976ad26d4fbcad0694aa3a08294af7fd5f759f

src/arduino/hid/Adafruit_USBD_HID.cpp, src/arduino/hid/Adafruit_USBD_HID.h, src/arduino/ports/nrf/tusb_config_nrf.h, src/arduino/ports/rp2040/tusb_config_rp2040.h, src/arduino/ports/samd/tusb_config_samd.h
Note: hid dual instances example is not added just yet, will do in a follow-up PR when having time.
=> enable multiple HID instances support, change CFG_TUD_HID=2 for all ports

.gitignore, examples/HID/hid_dual_interfaces/hid_dual_interfaces.ino
add multiple hid interface example
=> add multiple hid interfaces example

examples/DualRole/HID/hid_device_report/hid_device_report.ino, examples/DualRole/HID/hid_mouse_tremor_filter/hid_mouse_tremor_filter.ino
- add HID mouse tremor filter example for smoothing mouse movement
- butterworth_lowpass() is used with default SAMPLING_FREQUENCY = 100hz, CUTOFF_FREQUENCY = 10 hz. However, I am not sure what would be best freq configuration. 
@ladyada Probably need more tune up with either coeffs, filter algo but seems to work with shaking hands.
=> add mouse tremor with Butterworth filter

src/class/cdc/cdc_device.c, src/class/cdc/cdc_host.c, src/class/cdc/cdc_host.h, src/host/usbh.c, src/portable/chipidea/ci_hs/ci_hs_imxrt.h, src/tusb_option.h
update tinyusb to https://github.com/hathach/tinyusb/commit/2afef458be5ddea97d286f5dd8d3925c4846ee6e
=> update tinyusb core for Serial Host driver for ftdi/cp210x/ch9102f

src/arduino/cdc/Adafruit_USBH_CDC.cpp, src/arduino/cdc/Adafruit_USBH_CDC.h, src/class/cdc/cdc_host.c, src/class/cdc/cdc_host.h, src/host/usbh.c
more update to tinyusb core, enhance arduino Serial Host with 
- add mount/umount setDtrRts(), setBaudrate(), baud() for Serila Host
=> Enhance serial host

examples/DualRole/CDC/serial_host_bridge/serial_host_bridge.ino, examples/DualRole/HID/hid_device_report/hid_device_report.ino, examples/DualRole/HID/hid_mouse_log_filter/hid_mouse_log_filter.ino, examples/DualRole/HID/hid_mouse_tremor_filter/hid_mouse_tremor_filter.ino, examples/DualRole/HID/hid_remapper/hid_remapper.ino, examples/DualRole/MassStorage/msc_data_logger/msc_data_logger.ino, examples/DualRole/MassStorage/msc_file_explorer/msc_file_explorer.ino, examples/DualRole/device_info_rp2040/device_info_rp2040.ino
see this PR as a reference: https://github.com/sekigon-gonnoc/Pico-PIO-USB/pull/80
=> make DualRole sketches applicable for Pico W

src/common/tusb_common.h, src/common/tusb_debug.h, src/common/tusb_mcu.h, src/device/usbd.c, src/device/usbd.h, src/device/usbd_pvt.h, src/host/hcd.h, src/host/usbh.c, src/host/usbh_pvt.h, src/portable/analog/max3421/hcd_max3421.c, src/tusb.h
update tinyusb to get MAX3421e host driver support.
=> update tinyusb to commit 46f7cf4da2959b96d3af6b7f23d0d02ff7187f2f

examples/DualRole/CDC/serial_host_bridge/usbh_helper.h, examples/DualRole/HID/hid_device_report/usbh_helper.h, examples/DualRole/HID/hid_mouse_log_filter/hid_mouse_log_filter.ino, examples/DualRole/HID/hid_mouse_log_filter/usbh_helper.h, examples/DualRole/HID/hid_mouse_tremor_filter/hid_mouse_tremor_filter.ino, examples/DualRole/HID/hid_mouse_tremor_filter/usbh_helper.h, examples/DualRole/HID/hid_remapper/hid_remapper.ino, examples/DualRole/HID/hid_remapper/usbh_helper.h, examples/DualRole/MassStorage/msc_data_logger/msc_data_logger.ino, examples/DualRole/MassStorage/msc_data_logger/usbh_helper.h, examples/DualRole/MassStorage/msc_file_explorer/msc_file_explorer.ino, examples/DualRole/MassStorage/msc_file_explorer/usbh_helper.h, examples/DualRole/Simple/device_info/device_info.ino, examples/DualRole/Simple/device_info/usbh_helper.h
- cs, int are pin 10, 9
- remove GPIO0 as vbus enable
=> update featherwing host to new revision

.github/workflows/githubci.yml, examples/Host/Simple/host_device_info/host_device_info.ino, src/arduino/Adafruit_USBD_CDC.cpp, src/arduino/Adafruit_USBD_CDC.h, src/arduino/Adafruit_USBH_Host.h, src/arduino/ports/rp2040/tusb_config_rp2040.h
support rp2040 native usb host configuration
- add new example Host/Simple/host_device_info
- fix #292
require https://github.com/earlephilhower/arduino-pico/pull/1910
=> support rp2040 native usb host configuration

examples/DualRole/Simple/device_info_max3421e/device_info_max3421e.ino, src/arduino/Adafruit_USBH_Host.cpp, src/arduino/ports/rp2040/tusb_config_rp2040.h, src/portable/analog/max3421/hcd_max3421.c, src/portable/nordic/nrf5x/dcd_nrf5x.c, src/portable/raspberrypi/rp2040/hcd_rp2040.c
- update tinyusb, config and add rp2040 driver for max3421e as host
- add specific example for max3421e: device_info_max3421e
@jepler
=> Add rp2040 max3421e support

examples/DualRole/CDC/serial_host_bridge/usbh_helper.h, examples/DualRole/HID/hid_device_report/usbh_helper.h, examples/DualRole/HID/hid_mouse_log_filter/usbh_helper.h, examples/DualRole/HID/hid_mouse_tremor_filter/usbh_helper.h, examples/DualRole/HID/hid_remapper/usbh_helper.h, examples/DualRole/MassStorage/msc_data_logger/usbh_helper.h, examples/DualRole/MassStorage/msc_file_explorer/usbh_helper.h, examples/DualRole/Simple/device_info/usbh_helper.h, examples/DualRole/Simple/device_info_max3421e/device_info_max3421e.ino, examples/Host/Simple/host_device_info/host_device_info.ino
correct feather esp32 v2 with max3421e pin
=> correct feather esp32 v2 with max3421e pin

src/arduino/ports/esp32/tusb_config_esp32.h, src/arduino/ports/nrf/tusb_config_nrf.h, src/arduino/ports/rp2040/tusb_config_rp2040.h, src/arduino/ports/samd/tusb_config_samd.h, src/class/cdc/serial/ch34x.h
- follow up to #363 , enable CH34x configure
- add missing ch34x header
=> enable CFG_TUH_CDC_CH34X config for all ports

src/class/cdc/cdc_host.c
=> fix esp32 out of sync with esp core v2.0.14

src/arduino/ports/nrf/tusb_config_nrf.h, src/arduino/ports/rp2040/tusb_config_rp2040.h, src/arduino/ports/samd/tusb_config_samd.h
fix typo, fix #374, supersede and close #377
=> fix CFG_TUD_ENDPOINT0_SIZE typo

src/class/audio/audio_device.c, src/class/audio/audio_device.h, src/class/bth/bth_device.c, src/class/hid/hid_device.c, src/class/hid/hid_device.h, src/common/tusb_fifo.c, src/common/tusb_mcu.h, src/device/usbd.h, src/host/usbh.h, src/portable/analog/max3421/hcd_max3421.c, src/portable/nordic/nrf5x/dcd_nrf5x.c, src/portable/synopsys/dwc2/dcd_dwc2.c, src/portable/synopsys/dwc2/dwc2_esp32.h, src/tusb_option.h
update tinyusb to commit https://github.com/hathach/tinyusb/commit/55951b71aea46c09f27afe1640454fe43c983eec which include several fixes also include the fix to help https://github.com/adafruit/Adafruit_TinyUSB_Arduino/issues/436 with forcing disconnect/connect using otg pad
=> update tinyusb to commit 55951b71aea46c09f27afe1640454fe43c983eec

.github/workflows/githubci.yml, src/class/cdc/cdc_host.c, src/class/hid/hid_host.c, src/class/vendor/vendor_device.c, src/common/tusb_mcu.h, src/common/tusb_types.h, src/device/usbd.c, src/device/usbd_pvt.h, src/host/hub.c, src/host/usbh.c, src/host/usbh_pvt.h, src/osal/osal.h, src/osal/osal_freertos.h, src/osal/osal_mynewt.h, src/osal/osal_none.h, src/osal/osal_pico.h, src/osal/osal_rtthread.h, src/osal/osal_rtx4.h, src/osal/osal_zephyr.h, src/portable/analog/max3421/hcd_max3421.c, src/portable/synopsys/dwc2/dcd_dwc2.c, src/portable/synopsys/dwc2/dwc2_esp32.h
bump up tinyusb to commit e41a63c60dbebd9579698e6444bc62cfa518e15c
fix compiling hcd max3421e with arduino-esp32 and arduino-pico due to missing atomic_flag function
fix #513
=> fix compiling hcd max3421e with arduino-esp32 and arduino-pico due to missing atomic_flag function
