src/Adafruit_USBD_MIDI.cpp
src/Adafruit_USBD_MIDI.h

Allow to specify the number of virtual wires/plugs to be created for
the MIDI interface.
Initializing the MIDI device with:
Adafruit_USBD_MIDI usb_midi(3);
xports a single device with three separate ports/jacks/wires.
The ID (4 bit) of the jack/port is carried in the header packet of
the USB MIDI wire message.
--
This change requires the following change to the tinyusb core:
https://github.com/adafruit/ArduinoCore-samd/pull/179

MIDI: support virtual wires/plug

---

src/Adafruit_USBD_MIDI.h

Adafruit_USBD_MIDI implements Stream, and transitively Print. 
Print overloads write() with several versions, only one of which must be implemented, write(uint8_t).
Because Adafruit_USBD_MIDI declares write(uint8_t) in its class definition (as it must), it will _lose_ the overloaded versions, unless explicitly including them with a using declaration... Which is what this commit does.
Without this using declaration, users of this class cannot call write(const char* str) or write(const uint8_t *, size_t) as they would expect, since it inherits from Print.

allow use of all write() variants

---

src/Adafruit_USBD_HID.cpp

GCC catches this bug.
```
...\libraries\Adafruit_TinyUSB_Library\src\Adafruit_USBD_HID.cpp:
Line 181 Char 22
In member function 'bool Adafruit_USBD_HID::keyboardPress(uint8_t, char)':
warning: array subscript has type 'char' [-Wchar-subscripts]
181 |   if (_ascii2keycode[ch][0])
|                      ^~
...\libraries\Adafruit_TinyUSB_Library\src\Adafruit_USBD_HID.cpp:
Line 183 Char 31
warning: array subscript has type 'char' [-Wchar-subscripts]
183 |   keycode[0] = _ascii2keycode[ch][1];
|                               ^~
```

Use only unsigned value for array access

---

.github/workflows/githubci.yml

This add feather m4 can to ci build, need https://github.com/adafruit/ci-arduino/pull/93

add feather m4 can to ci build

---

src/Adafruit_TinyUSB.h
src/arduino/ports/Adafruit_TinyUSB_rp2040.cpp
src/arduino/ports/Adafruit_TinyUSB_samd.cpp

warn menu selection for port that has TinyUSB as optional menu specifically samd and rp2040

warn menu selection for port that has TinyUSB as optional menu

---

src/osal/osal_pico.h

For the Pico CI I use "-Werror -Wextra -Wall" which catches unused parameters
in a couple functions.  Add appropriate hints that the params are ignored.

Fix GCC -Wall -Wextra unused parameter warnings

---

examples/Composite/hid_generic_inout_ramdisk/hid_generic_inout_ramdisk.ino
examples/HID/hid_generic_inout/hid_generic_inout.ino
examples/HID/hid_keyboard/hid_keyboard.ino

Sorry for the piecemeal PRs!  I first got CI running with the library itself and only just was able to add in the examples.

Fix "-Wall -Wextra -Werror" warnings in examples

---

examples/HID/hid_gamepad/hid_gamepad.ino

This example is pending of modify PR https://github.com/adafruit/Adafruit_nRF52_Arduino/pull/622 and https://github.com/adafruit/Adafruit_TinyUSB_ArduinoCore/pull/20 changes.

Added HID Gamepad example

---

README.md
examples/Composite/hid_generic_inout_ramdisk/hid_generic_inout_ramdisk.ino
examples/Composite/mouse_external_flash/mouse_external_flash.ino
examples/Composite/mouse_ramdisk/mouse_ramdisk.ino
examples/HID/hid_composite/hid_composite.ino
examples/HID/hid_composite_joy_featherwing/hid_composite_joy_featherwing.ino
examples/HID/hid_gamepad/hid_gamepad.ino
examples/HID/hid_generic_inout/hid_generic_inout.ino
examples/HID/hid_keyboard/hid_keyboard.ino
examples/HID/hid_mouse/hid_mouse.ino
examples/MIDI/midi_pizza_box_dj/midi_pizza_box_dj.ino
examples/MIDI/midi_test/midi_test.ino
examples/MassStorage/msc_ramdisk/msc_ramdisk.ino
examples/MassStorage/msc_ramdisk_dual/msc_ramdisk_dual.ino
examples/WebUSB/webusb_rgb/webusb_rgb.ino
examples/WebUSB/webusb_serial/webusb_serial.ino
library.properties
src/Adafruit_TinyUSB.h
src/arduino/Adafruit_TinyUSB_API.cpp
src/arduino/Adafruit_USBD_CDC.cpp
src/arduino/Adafruit_USBD_Device.cpp
src/arduino/Adafruit_USBD_Device.h
src/arduino/hid/Adafruit_USBD_HID.cpp
src/arduino/midi/Adafruit_USBD_MIDI.cpp
src/arduino/msc/Adafruit_USBD_MSC.cpp
src/arduino/ports/rp2040/Adafruit_TinyUSB_rp2040.cpp
src/arduino/ports/rp2040/tusb_config_rp2040.h
src/arduino/webusb/Adafruit_USBD_WebUSB.cpp

This PR provide intial/experimental support for mbed core for rp2040 (core without built-in support). It is usable with TinyUSB, with a bit of limit such as: 
- `TinyUSB_Device_Init()` need to be manually called in setup()
- `TinyUSB_Device_Task()` and/or `TinyUSB_Device_FlushCDC()` may (or not) need to be manually called in loop()
- Use `SerialTinyUSB` name instead of Serial for serial monitor
- And there could be more other issues, using on these cores should be considered as experimental
Readme.md has been updated to clearly categorize core with and without built-in support.
I have tested with stock example: msc_ramdisk, hid_mouse/keyboard, midi_test, all seems to be working fine. However, since TinyUSB library **steal** all the usb packet/control and irq handler from mbed core, There …

Support rp2040 mbed

---

src/arduino/ports/nrf/Adafruit_TinyUSB_nrf.cpp

where init usb hardware cause USB IRQ to trigger before tusb is inited causing hardfault since usb control state (queue, task) is not inited. Should fix #107

nrf5x fix race condition

---

src/class/hid/hid.h

CR/LF was translating to keycode 0x9E, which is ignored by MacOS and Android. I have not tried other OSes. It should be keycode 0x28.

Newline generates a wrong keycode

---

src/arduino/Adafruit_USBD_Device.cpp
src/arduino/Adafruit_USBD_Device.h

Finally submitting something from my issue #85 from last year.
Tested with Adafruit NeoTrellis M4
usage:
```
char serialstr[32] = "mydev4676123";
USBDevice.setSerialDescriptor(serialstr);
```
and macOS reports `Serial Number:	mydev4676111` in the USB System Report for the device.

Set custom serial number

---

examples/MassStorage/msc_external_flash/msc_external_flash.ino
examples/MassStorage/msc_internal_flash_samd/msc_internal_flash_samd.ino

Add MSC example with internal flash example, implement #145 . The example is pretty much the same as External Flash one, except for the Adafruit_InternalFlash declaration instead of Adafruit_SPIFlash. This PR requires
- https://github.com/adafruit/ArduinoCore-samd/pull/316 to change bossac from 1.7 to 1.8 and  fake SPI interface for compiling with SdFat
- newly created library (not yet released and submitted to Arduino index) https://github.com/adafruit/Adafruit_InternalFlash . Please download/clone it to your lib folder in the meanwhile. Adafruit_InternalFlash is compatible with filesystem created by CircuitPython (switch between CP and Arduino will keep the FS intact) provided that the FS start address and size is configured correctly. For Adafruit SAMD21 board it should be
```C
// …
```

add msc internal flash samd example

---

examples/Composite/mouse_external_flash/mouse_external_flash.ino
examples/MassStorage/msc_external_flash/msc_external_flash.ino
examples/MassStorage/msc_external_flash_sdcard/msc_external_flash_sdcard.ino

- also remove ci skip test for rp2040 on msc external example
- ci currently failed since this requires https://github.com/adafruit/Adafruit_SPIFlash/pull/111 and a new release for SPI Flash library

update msc external flash example to work with rp2040

---

examples/MassStorage/msc_external_flash_sdcard/msc_external_flash_sdcard.ino
src/arduino/msc/Adafruit_USBD_MSC.cpp
src/class/audio/audio_device.c
src/class/audio/audio_device.h
src/class/hid/hid_device.h
src/class/msc/msc_device.c
src/class/msc/msc_device.h
src/class/usbtmc/usbtmc_device.c
src/common/tusb_compiler.h
src/common/tusb_fifo.c
src/common/tusb_verify.h
src/device/dcd.h
src/device/dcd_attr.h
src/device/usbd.c
src/osal/osal.h
src/portable/chipidea/ci_hs/ci_hs_imxrt.h
src/portable/chipidea/ci_hs/ci_hs_lpc18_43.h
src/portable/chipidea/ci_hs/ci_hs_type.h
src/portable/chipidea/ci_hs/dcd_ci_hs.c
src/portable/chipidea/ci_hs/hcd_ci_hs.c
src/portable/nordic/nrf5x/dcd_nrf5x.c
src/portable/raspberrypi/rp2040/dcd_rp2040.c
src/portable/raspberrypi/rp2040/hcd_rp2040.c
src/portable/raspberrypi/rp2040/rp2040_usb.c
src/tusb_option.h

- update tinyusb to https://github.com/hathach/tinyusb/commit/fcca8bb4ca219b2b43169997a5a00d65bc12c877
- response with illegal request to SCSI_CMD_PREVENT_ALLOW_MEDIUM_REMOVAL, required for macos for "sdcard reader" application
- update `msc_external_flash_sdcard.ino` example to work with dynamic sd card removal for board that support SD Detection pin e.g PyPortal.
@dhalbert [examples/MassStorage/msc_external_flash_sdcard/msc_external_flash_sdcard.ino](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/compare/msc-unit-ready?expand=1#diff-14ab6efd157f9212ace26549d297d7faa5a302e8ce60951645c27176bcd41be0) is the one that generates the test uf2

Enhance MSC multiple LUN with dynamic medium removal support

---

docs/examples/webusb-rgb/serial.js
docs/examples/webusb-serial/serial.js
examples/WebUSB/webusb_rgb/webusb_rgb.ino

I noticed that one onf the WebUSB examples was not compatible with the Arduino Nano rp2040.
And while I was working on that I also added the vendorId to the browser examples.

added example support for Arduino Nano RP2040 Connect

---

src/arduino/ports/rp2040/Adafruit_TinyUSB_rp2040.cpp

The hardcoded periodic USB task IRQ conflicts with the IRQ used by the
new Pico SDK 1.4.0 WiFi support.  A new API call was added in 1.4.0 to
allow the system to select a free IRQ, so use it.  Default to the
hardcoded one on earlier SDK versions (since those don't have the new
API call).
Fixes a crash found in https://github.com/earlephilhower/arduino-pico/pull/670

Dynamically pick task IRQ for Pico SDK 1.4.0

---

examples/DualRole/HID_device_report/HID_device_report.ino
src/arduino/Adafruit_USBH_Host.cpp

Add example for USB host HID report is simple, but need to modified `Adafruit_USBH_Host.cpp`.
Just need to add weak attribute to every HID callback.

add example for USB host HID report for RP2040

---

examples/MassStorage/msc_esp32_file_browser/msc_esp32_file_browser.ino
examples/MassStorage/msc_external_flash/flash_config.h
examples/MassStorage/msc_external_flash/msc_external_flash.ino
examples/MassStorage/msc_external_flash_sdcard/flash_config.h
examples/MassStorage/msc_external_flash_sdcard/msc_external_flash_sdcard.ino
examples/MassStorage/msc_internal_flash_samd/msc_internal_flash_samd.ino
examples/MassStorage/msc_sdfat/msc_sdfat.ino

some of new name such as File32 is not available in v1 (we can continue to use v1 symbol) but this is to illustrate how to migrate to SdFat v2. PR should work after 
- https://github.com/adafruit/Adafruit_SPIFlash/pull/127
- https://github.com/adafruit/SdFat/pull/13

Update msc sdfat example to work with SdFat v2

---

examples/DualRole/serial_host_bridge/serial_host_bridge.ino
src/Adafruit_TinyUSB.h
src/arduino/cdc/Adafruit_USBH_CDC.cpp
src/arduino/cdc/Adafruit_USBH_CDC.h
src/arduino/ports/rp2040/tusb_config_rp2040.h

- Add initial host cdc support with Adafruit_USBH_CDC class.
- Add DualRole/serial_host_bridge example to demonstrate how to use cdc host.

Add Host cdc support 

---

src/arduino/cdc/Adafruit_USBH_CDC.cpp
src/class/cdc/cdc_device.h
src/class/cdc/cdc_host.c
src/class/cdc/cdc_host.h
src/common/tusb_fifo.c
src/common/tusb_private.h

update tinyusb and arduino to include cdc host peek(), requried for stream API such as readUntil()

Add cdc host peek

---

examples/MIDI/midi_multi_ports/midi_multi_ports.ino
src/arduino/Adafruit_USBD_Device.cpp
src/arduino/Adafruit_USBD_Device.h
src/arduino/midi/Adafruit_USBD_MIDI.cpp
src/arduino/midi/Adafruit_USBD_MIDI.h

This patch allows to set custom descriptive names for virtual MIDI ports/cables. A MIDI port offers different functionality on the same physical USB device. The names make it easier to distinguish one from the other.
Edit: the tinyusb part was merged: https://github.com/hathach/tinyusb/pull/1738
```c
Device.usb.midi.setPortName(1, "Keyboard");
Device.usb.midi.setPortName(2, "Drum Pads");
Device.usb.midi.setPortName(3, "Lights");
```
```c
void setPorts(uint8_t n_ports) {
_midi.interface.setCables(n_ports);
}
void setPortName(uint8_t port, const char *name) {
_midi.interface.setCableNameStringIndex(port, _device.device->addStringToIndex(name));
}
```

MIDI: support port name strings

---

examples/DualRole/HID/hid_mouse_log_filter/hid_mouse_log_filter.ino

This filter seems to compensate for Essential Tremors better than the other.  YMMV, but I think this is a good starting point
Also, neither example sends through middle mouse, scroll wheel functions, etc.  I believe that's due to Thach's default being to use a Boot Mode Mouse, but it would be good to pass those through.

Add additional example for Tremors using a logarithm filter

---

examples/DualRole/CDC/serial_host_bridge/serial_host_bridge.ino
examples/DualRole/HID/hid_device_report/hid_device_report.ino
examples/DualRole/HID/hid_remapper/hid_remapper.ino
examples/DualRole/MassStorage/msc_data_logger/msc_data_logger.ino
examples/DualRole/MassStorage/msc_file_explorer/msc_file_explorer.ino
examples/DualRole/device_info_rp2040/device_info_rp2040.ino

hihi- just updating the `ifndef` pin names to match the [board def names](https://github.com/earlephilhower/arduino-pico/pull/1367/files) in some of the examples. looks like the updated pin names are not in the newest bsp release yet so also updating pin numbers to `16`-`18`.

Updating pin names for examples

---

examples/DualRole/CDC/serial_host_bridge/serial_host_bridge.ino
src/arduino/cdc/Adafruit_USBH_CDC.cpp

- USBH CDC setBaudrate() do nothing if baud is already matched
- begin() will also change baudrate if mounted()
- Update serial host example

Enhance Host CDC

---

.gitignore
examples/DualRole/CDC/serial_host_bridge/serial_host_bridge.ino
examples/DualRole/CDC/serial_host_bridge/usbh_helper.h
examples/DualRole/HID/hid_device_report/hid_device_report.ino
examples/DualRole/HID/hid_device_report/usbh_helper.h
examples/DualRole/HID/hid_mouse_log_filter/hid_mouse_log_filter.ino
examples/DualRole/HID/hid_mouse_log_filter/usbh_helper.h
examples/DualRole/HID/hid_mouse_tremor_filter/hid_mouse_tremor_filter.ino
examples/DualRole/HID/hid_mouse_tremor_filter/usbh_helper.h
examples/DualRole/HID/hid_remapper/hid_remapper.ino
examples/DualRole/HID/hid_remapper/usbh_helper.h
examples/DualRole/MassStorage/msc_data_logger/msc_data_logger.ino
examples/DualRole/MassStorage/msc_data_logger/usbh_helper.h
examples/DualRole/MassStorage/msc_file_explorer/msc_file_explorer.ino
examples/DualRole/MassStorage/msc_file_explorer/usbh_helper.h
examples/DualRole/Simple/device_info/device_info.ino
examples/DualRole/Simple/device_info/usbh_helper.h
examples/MassStorage/msc_ramdisk/msc_ramdisk.ino
src/arduino/Adafruit_TinyUSB_API.cpp
src/arduino/Adafruit_USBH_Host.cpp
src/arduino/Adafruit_USBH_Host.h
src/arduino/msc/Adafruit_USBH_MSC.cpp
src/arduino/ports/nrf/Adafruit_TinyUSB_nrf.cpp
src/arduino/ports/nrf/tusb_config_nrf.h
src/arduino/ports/rp2040/tusb_config_rp2040.h
src/arduino/ports/samd/Adafruit_TinyUSB_samd.cpp
src/arduino/ports/samd/tusb_config_samd.h
src/portable/analog/max3421/hcd_max3421.c

- Added max3421e (usb host shield) controller
- tested with nrf52 and samd21/samd51, work relatively well, there is a few hipcups, but it is due to tinyusb core (connection debouncing issue, will fix later)
- update all DualRole examples: CDC/serial_host_bridge, Simple/device_info, MassStorage/msc_file_explorer, HID/hid_device_report. Tested all feather nrf52840, metro m0 & m4 express, all seems to work well.
- Fix MSC host wait_for_io() issue when running with freeRTOS (e.g nrf52840).
PS: not tested with hub + device, hub + lowspeed device

Support max3421e (usb host shield) for nrf52 and samd21/samd51

---

library.json

This adds platformio compatibility, when this library is pulled as a gitsubmodule (e.g. in adafruit's nrf52 framework). More infos here: https://docs.platformio.org/en/latest/manifests/library-json/index.html
Related to my efforts of adding "real" platformio compatibility to Adafruit's nrf52 framework, see also https://github.com/adafruit/Adafruit_nRFCrypto/pull/6 .
Hoping for your feedback!

Add platformio compatibility

---

examples/DualRole/CDC/serial_host_bridge/usbh_helper.h
examples/DualRole/HID/hid_device_report/usbh_helper.h
examples/DualRole/HID/hid_mouse_log_filter/usbh_helper.h
examples/DualRole/HID/hid_mouse_tremor_filter/usbh_helper.h
examples/DualRole/HID/hid_remapper/usbh_helper.h
examples/DualRole/MassStorage/msc_data_logger/usbh_helper.h
examples/DualRole/MassStorage/msc_file_explorer/usbh_helper.h
examples/DualRole/Simple/device_info/usbh_helper.h
src/arduino/Adafruit_USBH_Host.cpp
src/arduino/Adafruit_USBH_Host.h
src/portable/analog/max3421/hcd_max3421.c
tools/update-usbh_helper.py

- change USBHost declaration with spi pin for esp32 to make it easier to select spi hardware module

change USBHost declaration with spi pin for esp32

---

src/arduino/Adafruit_USBH_Host.cpp
src/portable/analog/max3421/hcd_max3421.c

this is correct implementation to share SPI with other peripherals. Therefore hcd_init() should not call this, only when start/end a transfer

move SPI beginTransaction()/endTransaction() to tuh_max3421_spi_cs_api()

---

src/arduino/Adafruit_TinyUSB_API.cpp
src/arduino/ports/rp2040/tusb_config_rp2040.h
src/common/tusb_mcu.h
src/device/usbd.h
src/host/usbh.c
src/portable/raspberrypi/pio_usb/hcd_pio_usb.c
src/tusb_option.h

- fix race condtion described in https://github.com/hathach/tinyu…sb/pull/2310
- cause esp32s3 tester not able to enumerate after flashed (since the device flip/reset back and forth between boot/jtag/app)
- may also need https://github.com/sekigon-gonnoc/Pico-PIO-USB/pull/104
PS: This update skip changes in audio_device.c/h comparing to core master
@ladyada

update tinyusb to fix race condition 

---

examples/DualRole/CDC/serial_host_bridge/usbh_helper.h
examples/DualRole/HID/hid_device_report/usbh_helper.h
examples/DualRole/HID/hid_mouse_log_filter/hid_mouse_log_filter.ino
examples/DualRole/HID/hid_mouse_log_filter/usbh_helper.h
examples/DualRole/HID/hid_mouse_tremor_filter/hid_mouse_tremor_filter.ino
examples/DualRole/HID/hid_mouse_tremor_filter/usbh_helper.h
examples/DualRole/HID/hid_remapper/hid_remapper.ino
examples/DualRole/HID/hid_remapper/usbh_helper.h
examples/DualRole/MassStorage/msc_data_logger/msc_data_logger.ino
examples/DualRole/MassStorage/msc_data_logger/usbh_helper.h
examples/DualRole/MassStorage/msc_file_explorer/msc_file_explorer.ino
examples/DualRole/MassStorage/msc_file_explorer/usbh_helper.h
examples/DualRole/Simple/device_info/device_info.ino
examples/DualRole/Simple/device_info/usbh_helper.h
src/arduino/Adafruit_USBH_Host.cpp
src/arduino/Adafruit_USBH_Host.h
src/arduino/ports/esp32/tusb_config_esp32.h
src/tusb_config.h

Add support for featherwing USB host with max3421e
- add max3421_readRegister() max3421_readRegister(), max3421_writeIOPINS1(), max3421_writeIOPINS2() to usbhost with max3421
- update examples to work with featherwing usb host max3421, added max3421's GPIO0 pull up (VBUS enable) after host init
- Update tinyusb to also support non-OTG MCU such as esp32 (not tested with c3, c6 etc..)
- Tested with feather m0, m4, nrf52840, esp32s2, esp32s3, esp32 v2
@ladyada

Support featherwing max3421

---

src/arduino/Adafruit_USBD_CDC.cpp
src/class/audio/audio_device.c
src/class/cdc/cdc_host.c
src/common/tusb_mcu.h
src/common/tusb_verify.h
src/device/dcd.h
src/device/usbd.c
src/device/usbd.h
src/device/usbd_control.c
src/host/hub.c
src/host/usbh.c
src/host/usbh.h
src/host/usbh_pvt.h
src/tusb_option.h

Change tuh_event_hook_cb, tud_event_hook_cb to weak default implementation, shoul fix #357

update tinyusb to pr https://github.com/hathach/tinyusb/pull/2412

---

src/class/cdc/cdc.h
src/class/cdc/cdc_host.c
src/class/cdc/cdc_host.h
src/class/cdc/serial/cp210x.h
src/class/cdc/serial/ftdi_sio.h
src/common/tusb_common.h
src/tusb_option.h

update tinyusb for host serial ch34x support https://github.com/hathach/tinyusb/pull/2391

update tinyusb for ch34x host support

---

examples/Video/video_capture/usb_descriptors.h
examples/Video/video_capture/video_capture.ino
src/Adafruit_TinyUSB.h
src/arduino/Adafruit_USBD_Device.cpp
src/arduino/ports/nrf/tusb_config_nrf.h
src/arduino/ports/rp2040/tusb_config_rp2040.h
src/arduino/ports/samd/tusb_config_samd.h
src/arduino/video/Adafruit_USBD_Video.cpp
src/arduino/video/Adafruit_USBD_Video.h

- initial support for UVC
- Add new Adafruit_USBD_Video.cpp/h but it is only used to build configuration descriptor for now. All APIs use native tinyusb tud_video_ call
- Update USBD Device configuration descriptor builder to update/adjust interface number, endpoint address dynamically for video class
- add video_capture.ino example
- enable bulk video streaming for rp2040/samd21/samd51/nrf52840
@ladyada

Add Video class support

---

.github/workflows/githubci.yml
examples/Vendor/i2c_tiny_usb_adapter/Adafruit_USBD_I2C.cpp
examples/Vendor/i2c_tiny_usb_adapter/Adafruit_USBD_I2C.h
src/arduino/Adafruit_TinyUSB_API.h
src/arduino/Adafruit_USBD_CDC.cpp
src/arduino/Adafruit_USBD_CDC.h
src/arduino/Adafruit_USBD_Device.cpp
src/arduino/Adafruit_USBD_Device.h
src/arduino/Adafruit_USBD_Interface.cpp
src/arduino/Adafruit_USBD_Interface.h
src/arduino/hid/Adafruit_USBD_HID.cpp
src/arduino/hid/Adafruit_USBD_HID.h
src/arduino/midi/Adafruit_USBD_MIDI.cpp
src/arduino/midi/Adafruit_USBD_MIDI.h
src/arduino/msc/Adafruit_USBD_MSC.cpp
src/arduino/msc/Adafruit_USBD_MSC.h
src/arduino/video/Adafruit_USBD_Video.h
src/arduino/webusb/Adafruit_USBD_WebUSB.cpp
src/arduino/webusb/Adafruit_USBD_WebUSB.h

rework configuration builder, remove auto interface and endpoint numbering. Leave that to each interface instead. Add
- Adafruit_USBD_Device: allocInterface(), allocEndpoint()
- change Adafruit_USBD_Interface::setStringDescriptor() to use Adafruit_USBD_Device::addStringDescriptor() and store _strid.
- Update all class driver interface to use new configuration API(): CDC, MSC, HID, MIDI, Vendor, Webusb

Rework config descriptor builder

---

src/arduino/video/Adafruit_USBD_Video.cpp

GCC 12 complains when a structure member is not initialized, so set a sane default value.
Fixes #385

Fix GCC 12.3 warning in USB Video core

---

src/arduino/Adafruit_USBD_Device.h
src/arduino/Adafruit_USBH_Host.cpp
src/class/cdc/cdc_host.c
src/class/net/ncm_device.c

fix #387 failed to compile with esp32 v2

fix build with esp32 v2

---

src/arduino/hid/Adafruit_USBD_HID.cpp
src/arduino/hid/Adafruit_USBD_HID.h

Add a getProtocol method, allowing an application to query whether the HID interface is currently set to Boot or Report Protocol.
Fixes #381.

add Adafruit_USBD_HID::getProtocol

---

.github/workflows/githubci.yml
src/arduino/Adafruit_TinyUSB_API.cpp

- fix #384 
- also add rp2040 tinyusb native host to ci build

Fix  undefined reference to `log_printf' when enable debug with native usb host

---

examples/Vendor/i2c_tiny_usb_adapter/Adafruit_USBD_I2C.cpp

Fixes GCC 12 warning for unused parameter found in CI [here](https://productionresultssa0.blob.core.windows.net/actions-results/86f8a27f-af5f-41d2-ac6a-ab59c6755d8e/workflow-job-run-77c9e3e1-c72c-50bc-55af-3e7adcee1252/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-03-07T20%3A32%3A23Z&sig=l%2FfxguicbywzgOodDk7iKkFiXcDfjWhvO9lVLQaLCy0%3D&sp=r&spr=https&sr=b&st=2024-03-07T20%3A22%3A18Z&sv=2021-12-02): 
````
/home/runner/work/arduino-pico/arduino-pico/libraries/Adafruit_TinyUSB_Arduino/examples/Vendor/i2c_tiny_usb_adapter/Adafruit_USBD_I2C.cpp:67:60: error: unused parameter 'itfnum_deprecated' [-Werror=unused-parameter]
67 | uint16_t Adafruit_USBD_I2C::getInterfaceDescriptor(uint8_t itfnum_deprecated, uint8_t* buf, uint16_t bufsize) {
| …
```

Remove GCC 12 warning in Vendor example

---

src/arduino/ports/nrf/tusb_config_nrf.h
src/arduino/ports/rp2040/tusb_config_rp2040.h
src/arduino/ports/samd/tusb_config_samd.h

This allows a board definition to override interface counts on the compiler command line, instead of replacing the entire tusb_config.h file.

allow override of TUD interface counts

---

examples/DualRole/Simple/device_info_max3421e/device_info_max3421e.ino
src/common/tusb_verify.h

use correct pin D8, D7 for feather c6 in max3421e sketch

---

examples/CDC/cdc_multi/.skip.txt
examples/CDC/serial_echo/serial_echo.ino
src/Adafruit_TinyUSB.h
src/arduino/Adafruit_TinyUSB_API.h
src/arduino/Adafruit_USBD_CDC.cpp
src/arduino/Adafruit_USBD_CDC.h
src/arduino/Adafruit_USBD_Interface.h
src/arduino/midi/Adafruit_USBD_MIDI.cpp
src/arduino/msc/Adafruit_USBD_MSC.cpp
src/arduino/ports/ch32/Adafruit_TinyUSB_ch32.cpp
src/arduino/ports/ch32/tusb_config_ch32.h
src/arduino/video/Adafruit_USBD_Video.cpp
src/arduino/webusb/Adafruit_USBD_WebUSB.cpp
src/common/tusb_mcu.h
src/portable/st/stm32_fsdev/fsdev_ch32.h
src/portable/wch/ch32_usbfs_reg.h
src/portable/wch/ch32_usbhs_reg.h
src/tusb_config.h
src/tusb_option.h

- add built-in core support for ch32, this requires PR to ch32 core to be merged to work with
- tested with ch32v203 and ch32v307 (require 144Hz HSE)
- update tinyusb lib to support highspeed bulk (512 bytes) endpoint
- try to support ch32v10x but doesn't work.

Add Ch32 built-inn core support

---

src/portable/st/stm32_fsdev/dcd_stm32_fsdev.c
src/portable/st/stm32_fsdev/fsdev_type.h

update tinyusb to include more fix for fsdev ch32v203
- https://github.com/hathach/tinyusb/pull/2761 fix more race when using with hub with setup/out
- https://github.com/hathach/tinyusb/pull/2762 fix iso issue introduced by driver rework

update tinyusb to fix ch32v203 race with hub in setup

---

examples/CDC/cdc_multi/cdc_multi.ino
examples/CDC/no_serial/no_serial.ino
examples/Composite/mouse_ramdisk/mouse_ramdisk.ino
examples/HID/hid_boot_keyboard/hid_boot_keyboard.ino
examples/HID/hid_boot_mouse/hid_boot_mouse.ino
examples/HID/hid_composite/hid_composite.ino
examples/HID/hid_composite_joy_featherwing/hid_composite_joy_featherwing.ino
examples/HID/hid_dual_interfaces/hid_dual_interfaces.ino
examples/HID/hid_gamepad/hid_gamepad.ino
examples/HID/hid_generic_inout/hid_generic_inout.ino
examples/MIDI/midi_multi_ports/midi_multi_ports.ino
examples/MIDI/midi_test/midi_test.ino
examples/MassStorage/msc_esp32_file_browser/msc_esp32_file_browser.ino
examples/MassStorage/msc_external_flash/msc_external_flash.ino
examples/MassStorage/msc_external_flash_sdcard/msc_external_flash_sdcard.ino
examples/MassStorage/msc_internal_flash_samd/msc_internal_flash_samd.ino
examples/MassStorage/msc_ramdisk/msc_ramdisk.ino
examples/MassStorage/msc_ramdisk_dual/msc_ramdisk_dual.ino
examples/MassStorage/msc_sd/msc_sd.ino
examples/MassStorage/msc_sdfat/msc_sdfat.ino
examples/Vendor/i2c_tiny_usb_adapter/i2c_tiny_usb_adapter.ino
examples/Video/video_capture/video_capture.ino
examples/WebUSB/webusb_rgb/webusb_rgb.ino
examples/WebUSB/webusb_serial/webusb_serial.ino

For some fast chip such as esp32-s3, by the time we initialize class driver enumeration process is already done. Therefore we will need to force re-enumeration using disconnect/connect. Should fix https://github.com/adafruit/Adafruit_TinyUSB_Arduino/issues/436

force re-enumerate for all examples.

---

src/arduino/ports/rp2040/tusb_config_rp2040.h

We utilize multiple serial ports on RP2040 boards.  We do so today by manually editing the library (the change is committed).  I can verify the RP2040 has no problem running multiple USB Serial Interfaces at the same time.
Example below how to initialize in .ino file for 2 Serial ports at same time,
```
#include <Adafruit_TinyUSB.h>
Adafruit_USBD_CDC USBSer1;
// In setup method
// Setup Serial
Serial.begin(115200);
// initialize 2nd CDC interface
USBSer1.begin(3686400);
```

Enable multiple serial over usb for rp2040

---

library.json

Brings libraryçjson up to date to todays standards. 
Without the platforms field, platformio pioarduino esp32 core fails with:
Testing platformio.ini:
```ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
build_cache_dir = .cache
[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32.git#develop
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = 
-D ARDUINO_USB_MODE=1
-D …
```

Bring library.json up to date

---

src/host/hub.c
src/host/usbh.c

@ladyada this should help with our store's mouse issue

fix sigma mouse in adafruit store cause multiple attach connection

---

src/arduino/Adafruit_USBD_Device.cpp

Looking at Adafruit_USBD_Device.cpp, there's a define macro for the Max Power but it's never used.
at line 85:
```
#ifndef USB_CONFIG_POWER
#define USB_CONFIG_POWER 100
#endif
```
At line 186, the power is hardcoded to 100:
```
uint8_t const dev_cfg[sizeof(tusb_desc_configuration_t)] = {
TUD_CONFIG_DESCRIPTOR(1, 0, 0, sizeof(tusb_desc_configuration_t),
TUSB_DESC_CONFIG_ATT_REMOTE_WAKEUP | TU_BIT(7),
100),
};
```
I simply replaced the 100 with USB_CONFIG_POWER.

USB Device Descriptor Max Power is not configurable #504

---

.github/ISSUE_TEMPLATE/bug_report.yml
src/arduino/Adafruit_USBD_Device.h

follow up to #505 , fix #421
This pull request introduces two new methods to the `Adafruit_USBD_Device` class in `src/arduino/Adafruit_USBD_Device.h` to enhance configuration management for USB devices. These changes allow setting configuration attributes and specifying maximum power consumption.
* **Added `setConfigurationAttribute` method**: This method allows setting the configuration attribute by modifying the `bmAttributes` field in the configuration descriptor.
* **Added `setConfigurationMaxPower` method**: This method enables setting the maximum power consumption (in mA) for the USB device, with a validation check to ensure the value does not exceed the USB specification's limit of 510mA.

add setConfigurationMaxPower() and setConfigurationAttribute

---

examples/MassStorage/msc_external_flash_sdcard/msc_external_flash_sdcard.ino
examples/MassStorage/msc_sdfat/msc_sdfat.ino

This pull request introduces improvements to SD card handling and code style consistency in two example files: `msc_external_flash_sdcard.ino` and `msc_sdfat.ino`. The changes include adding SD card configuration for the `ARDUINO_ADAFRUIT_METRO_RP2040` board, enhancing SD card initialization logic, and cleaning up code formatting for better readability.
* Added specific `SDCARD_CS`, `SDCARD_DETECT`, and `SDCARD_DETECT_ACTIVE` definitions for the `ARDUINO_ADAFRUIT_METRO_RP2040` board in `msc_external_flash_sdcard.ino` and `msc_sdfat.ino`, ensuring compatibility with this board. [[1]](diffhunk://#diff-14ab6efd157f9212ace26549d297d7faa5a302e8ce60951645c27176bcd41be0R50-R54) [[2]](diffhunk://#diff-cb22a8910f3ba795d02518ee6d091215256a0fe85f4a6a5eb55478f72572ccc9L13-R36)
* Updated …

update msc sdcad example to work with metro rp2040

---

examples/MassStorage/msc_external_flash_sdcard/msc_external_flash_sdcard.ino
examples/MassStorage/msc_sdfat/msc_sdfat.ino

- use SDIO (pio) for rp2040/rp2350
- remove printing flash/sdcard contents to Serial since it conflict with host, which can cause conflict in spi/sdio transport and/or correupt cache,sector
- This "fix" completely remove the sdcard contents dump. a better fix would be marking the SDcard as not ready (return false in TEST_UNIT_READY) while performming self-reading, but that would maybe take a bit of time. I will do it later if needed. 
- supercede and close #532 fix #455
@mikeysklar let me know if this works for you (you need to update Sdfat to v2.3.50)
PS: The conflict happen with macos more often since macos does lots of hidden writing of meta data file e.g `.DS_Store`

resolve msc sdcard example conflict with host espcially macos
